#!/bin/sh

config=(
  mouse_follows_focus on
  focus_follows_mouse autoraise
  window_origin_display default
  window_placement second_child
  window_zoom_persist on
  window_topmost off
  window_shadow on
  window_animation_frame_rate 120
  window_animation_duration 0.2
  window_opacity_duration 0.0
  active_window_opacity 1.0
  normal_window_opacity 0.90
  window_opacity off
  insert_feedback_color 0xffd75f5f
  window_border_width 4
  window_border_radius 12
  window_border_blur off
  window_border_hidpi on
  window_border on
  split_ratio 0.50
  split_type auto
  auto_balance on
  left_padding 12
  right_padding 12
  top_padding 5
  bottom_padding 10
  window_gap 5
  layout bsp
  mouse_modifier cmd
  mouse_action1 move
  mouse_action2 resize
  mouse_drop_action swap
  active_window_border_color 0xFFC099FF
  normal_window_border_color 0xFF444A73
)

yabai -m config ${config[@]}

# sudo yabai --load-sa

# in external display, top padding is different
# on M1 or later macbook, the notch space working as padding
 DISPLAY_UUID=37D8832A-2D66-02CA-B9F7-8F30A301B230 # UUID of built-in display
 BAR_PADDING=40
 SPACES_ON_SUB=$(yabai -m query --displays | jq ".[] | select(.uuid != \"${DISPLAY_UUID}\") | .spaces[]")
 for idx in ${SPACES_ON_SUB}
 do
     yabai -m config --space "$idx" top_padding "$BAR_PADDING"
 done

rules=(
  app="^System Settings" sticky=on layer=above manage=off
  app="^Finder" sticky=on layer=above manage=off
  app="^WhatsApp" sticky=on layer=above manage=off
  app="^Facetime" sticky=on layer=above manage=off
  app="^Raycast" sticky=on layer=above manage=off
  app="^Music" sticky=on layer=above manage=off
  app="^Reminders" sticky=on layer=above manage=off
)

yabai -m rule --add ${rules[@]}

# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# yabai -m signal --add event=space_changed action="/Users/moritzdresch/.config/sketchybar/plugins/spaces.sh"

