general.import = [
  # uncomment the flavour you want below:
  "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "UDEV Gothic 35NFLG", style = "Regular" }
size = 16.0
offset = { x = 1, y = 1 }

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless" 
opacity = 0.7
blur = true
